name: travelecho
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pinput: ^5.0.0
  carousel_slider: 
  font_awesome_flutter: ^10.8.0
  #icons
  flutter_feather_icons: ^2.0.0+1
  eva_icons_flutter: ^3.1.0
  heroicons: ^0.10.0
  line_icons: ^2.0.3
  #date_picker
  date_picker_plus: ^4.1.0
  provider: ^6.1.2
  # flutter_svg: ^2.0.16
  camera: 
  path_provider: ^2.0.10
  image_picker: 
  gal:
    # Fetch Data From Api
  dio: ^5.7.0
  # Handle Success/Error State From Data Source
  dartz:
    ^0.10.1
    # BloC State Management
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  # Json Annotation
  json_annotation:
    ^4.9.0
    # Being able to compare objects in Dart
  equatable: ^2.0.7
  logger: ^2.5.0
  shared_preferences: ^2.3.0
  # note: A flutter plugin for adapting screen and font size.Let your UI display a reasonable layout on different screen sizes!
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializer: ^0.2.0
  build_runner: ^2.4.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/travel_echo_logo.png" # Path to your logo
  adaptive_icon_background: "#ffffff" # Optional for Android adaptive icons

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/json/occupations.json
    - assets/json/language-list-json.json
    - assets/json/hobbies.json
    - assets/images/
    - assets/images/auth/
    - assets/images/home_images/
    - assets/images/currency_converter/
    - assets/images/budget/
    - assets/images/milestones/
    - assets/images/trip_images/
    - assets/images/memories/
    - assets/images/culture_guide/
    - assets/images/profile/
    - assets/images/onboarding/
    - assets/images/community/
    - assets/images/auth/welcome_gif.gif


  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: vaio_con_dios
      fonts:
        - asset: assets/fonts/vaio_con_dios/_IO CON DIOS.otf
    - family: segoe_ui
      fonts:
        - asset: assets/fonts/segoe-ui-this/segoeuithibd.ttf
          weight: 700 # Use numeric weights for bold
        - asset: assets/fonts/segoe-ui-this/segoeuithis.ttf
          weight: 400 # Normal font weight
        - asset: assets/fonts/segoe-ui-this/segoeuithisi.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/segoe-ui-this/segoeuithisz.ttf
          style: italic
          weight: 700
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
